defmodule Torrent do
  use Supervisor, type: :supervisor, restart: :transient
  use Via

  @type hash :: <<_::160>>
  @type hash_v2 :: <<_::256>>
  @type kind :: :v1 | :hybrid | :v2
  @type index :: non_neg_integer()
  @type begin :: non_neg_integer()
  @type length :: pos_integer()
  @type block :: iodata()
  @type bitfield :: binary()
  @type speed :: %{:download => non_neg_integer(), :upload => non_neg_integer()}

  @empty 0
  @completed 1
  @started 2
  @stopped 3

  @enforce_keys [:hash, :metadata, :left, :last_index, :last_piece_length]
  defstruct [
    :hash,
    :metadata,
    :left,
    :last_index,
    :last_piece_length,
    :added_at,
    :download_dir,
    :info_blob,
    :hash_v2,
    :merkle,
    bitfield: nil,
    peer_status: nil,
    uploaded: 0,
    downloaded: 0,
    event: @started,
    speed: %{download: 0, upload: 0},
    private?: false,
    kind: :v1
  ]

  @type t :: %__MODULE__{
          # urlencoded 20-byte string used as a unique ID for the client,
          # generated by the client at startup
          hash: hash(),
          metadata: map(),
          # The number of bytes this client still has to download in base
          # ten ASCII. Clarification:
          # The number of bytes needed to download to be 100% complete
          # and get all the included files in the torrent.
          left: non_neg_integer(),
          last_index: index(),
          last_piece_length: length(),
          added_at: DateTime.t() | nil,
          peer_status: Peer.status(),
          # The total amount uploaded
          # (since the client sent the 'started' event to the tracker)"""
          uploaded: non_neg_integer(),
          # The total amount downloaded
          # (since the client sent the 'started' event to the tracker)"""
          downloaded: non_neg_integer(),
          # "started" | "empty" | "completed" | "stopped"
          event: 0..3,
          speed: speed(),
          bitfield: bitfield() | nil,
          private?: boolean(),
          info_blob: binary() | nil,
          # BEP 52 § Info dictionary — nil for v1 torrents; SHA-256 of raw
          # info_blob for hybrid and v2. Kept alongside the v1 SHA-1 `hash`
          # (which stays the wire/tracker/DHT identifier throughout).
          hash_v2: hash_v2() | nil,
          # Parsed and root-validated BEP 52 per-file piece hashes. Nil for v1.
          merkle: Torrent.Merkle.metadata_context() | nil,
          # BEP 52 § Compatibility — :v1 = no `meta version`; :hybrid = v1 +
          # v2 fields in same info dict; :v2 = only v2 (pure BEP 52).
          kind: kind()
        }

  alias __MODULE__.{
    Controller,
    Swarm,
    # Bitfield,
    PiecesStatistic,
    FileHandle,
    Uploader,
    Downloads,
    Files,
    Model,
    Resume,
    Session
  }

  @spec start_link(Path.t() | {Path.t(), keyword()}) :: Supervisor.on_start() | none()
  def start_link({path, opts}) when is_binary(path) and is_list(opts),
    do: Supervisor.start_link(__MODULE__, {path, opts})

  def start_link(path) when is_binary(path),
    do: start_link({path, []})

  @compile {:inline, empty: 0, started: 0, completed: 0, stopped: 0, event_to_string: 1}

  def started(), do: @started

  def empty(), do: @empty

  def completed(), do: @completed

  def stopped(), do: @stopped

  @spec event_to_string(0..3) :: String.t()
  def event_to_string(@empty), do: "empty"

  def event_to_string(@completed), do: "completed"

  def event_to_string(@started), do: "started"

  def event_to_string(@stopped), do: "stopped"

  def hex_encoded_hash(hash) do
    hash
    |> :crypto.bytes_to_integer()
    |> Integer.to_string(16)
    |> String.pad_leading(byte_size(hash) * 2, "0")
  end

  defdelegate has_hash?(hash), to: Model

  defdelegate add_peer(hash, id, reserved, socket), to: Swarm, as: :add

  defdelegate have?(hash, index), to: PiecesStatistic

  defdelegate get(hash), to: Model

  defdelegate get(hash, key), to: Model

  defdelegate downloaded?(hash), to: Model

  defdelegate list_files(hash), to: Files, as: :list

  defdelegate file_count(hash), to: Files, as: :count

  @spec get_hash(pid()) :: Torrent.hash() | nil
  def get_hash(pid) do
    case Registry.lookup(Registry, pid) do
      [{_, hash}] ->
        hash

      _ ->
        nil
    end
  end

  defdelegate stop(pid), to: Supervisor

  def init({path, opts}) when is_binary(path) and is_list(opts) do
    download_dir = normalize_download_dir(Keyword.get(opts, :download_dir))
    %Torrent{hash: hash} = torrent = parse_file!(path) |> Map.put(:download_dir, download_dir)
    start_torrent(torrent, hash, opts)
  end

  def init(path) when is_binary(path), do: init({path, []})

  defp start_torrent(%Torrent{hash: hash} = torrent, hash, opts) do
    {torrent, resume_mode} = resume_mode_for(torrent, hash, opts)

    PiecesStatistic.init(torrent)

    children = [
      {Model, torrent},
      {FileHandle, hash},
      {Uploader, hash},
      {Torrent.HashServe, hash},
      {Downloads, hash},
      {Swarm, hash},
      {Peer.ConnectionManager, hash},
      {Controller, hash},
      Resume.child_spec({hash, resume_mode}),
      # WebSeed (BEP 19) — placed after Resume so a WebSeed crash never
      # cascades a Resume restart under `:rest_for_one` (Resume re-runs the
      # full-disk verify which is expensive). Returns :ignore when the
      # metadata carries no `url-list`, which is the common case.
      {Torrent.WebSeed, hash}
    ]

    # Resume is last: when it exits normally after disk verify, :rest_for_one must
    # NOT restart Downloads/Controller (unlike :one_for_all which killed Downloads
    # mid-piece and re-ran verify in a loop).
    opts = [strategy: :rest_for_one, max_restarts: 3]

    return = Supervisor.init(children, opts)

    case Registry.register(Registry, self(), hash) do
      {:ok, _} -> :ok
      {:error, {:already_registered, pid}} when is_pid(pid) -> :ok
    end

    PeerDiscovery.register(self(), torrent)

    return
  end

  @spec resume_mode_for(Torrent.t(), Torrent.hash(), keyword()) ::
          {Torrent.t(), Torrent.Resume.mode()}
  defp resume_mode_for(torrent, hash, opts) do
    case Keyword.fetch(opts, :resume) do
      {:ok, mode} ->
        case Session.load(hash) do
          {:ok, session} -> {Session.apply(torrent, session), mode}
          :error -> {torrent, mode}
        end

      :error ->
        case Session.load(hash) do
          {:ok, session} -> {Session.apply(torrent, session), :verify_saved}
          # Fresh .torrent add: empty bitfield → :verify_saved checks 0 indices.
          # :full_scan would SHA-1 every sparse-prealloc piece (failed=N/N noise).
          :error -> {torrent, :verify_saved}
        end
    end
  end

  @spec normalize_download_dir(nil | Path.t()) :: Path.t()
  defp normalize_download_dir(nil), do: File.cwd!()

  defp normalize_download_dir(dir) when is_binary(dir) do
    dir = Path.expand(dir)
    File.mkdir_p!(dir)
    dir
  end

  @spec parse_file!(Path.t()) :: t() | no_return()
  def parse_file!(path) do
    raw = File.read!(path)
    metadata = Bento.decode!(raw)
    info_blob = slice_info_blob!(raw)

    kind = detect_kind(metadata)

    if kind == :v2 do
      # BEP 52 pure-v2 needs merkle-tree verification, piece-layers
      # bookkeeping and the hash-request/hashes/hash-reject extension
      # messages before any bytes can be trusted. Hybrid torrents fall
      # through to the v1 code path (they carry both `pieces` and
      # `file tree`); a peer that only ever speaks v2 would still be
      # reachable via the truncated v2 info-hash — deferred to a later
      # BEP 52 phase.
      raise ArgumentError,
            "BitTorrent v2 (BEP 52) pure-v2 torrents are not yet supported — " <>
              "missing v1 `pieces` field. Hybrid v1+v2 torrents load normally."
    end

    merkle = merkle_for(kind, metadata)
    bytes = all_bytes_in_torrent(metadata)

    last_index =
      metadata["info"]["pieces"]
      |> byte_size()
      |> div(20)
      |> Kernel.-(1)

    %__MODULE__{
      hash: :crypto.hash(:sha, info_blob),
      hash_v2: hash_v2_for(kind, info_blob),
      merkle: merkle,
      kind: kind,
      left: bytes,
      last_piece_length: bytes - last_index * metadata["info"]["piece length"],
      metadata: metadata,
      last_index: last_index,
      private?: private?(metadata),
      info_blob: info_blob
    }
  end

  @doc """
  Classifies a decoded torrent metadata map as `:v1`, `:hybrid`, or `:v2`.

  Per BEP 52 §5: v2 torrents set `info["meta version"] = 2`. A torrent that
  keeps the v1 `info["pieces"]` list alongside the v2 `info["file tree"]` /
  `info["meta version"] = 2` fields is a hybrid (both info-hashes address the
  same content, aligned via BEP 47 padding files). A v2-only torrent has
  `meta version = 2` and no `pieces`.
  """
  @spec detect_kind(map()) :: kind()
  def detect_kind(%{"info" => info}) when is_map(info) do
    meta_v2? = Map.get(info, "meta version") == 2 or Map.has_key?(info, "file tree")
    v1? = is_binary(Map.get(info, "pieces"))

    cond do
      meta_v2? and v1? -> :hybrid
      meta_v2? -> :v2
      true -> :v1
    end
  end

  def detect_kind(_), do: :v1

  @spec hash_v2_for(kind(), binary()) :: hash_v2() | nil
  defp hash_v2_for(:v1, _blob), do: nil
  defp hash_v2_for(_kind, blob), do: :crypto.hash(:sha256, blob)

  @spec merkle_for(kind(), map()) :: Torrent.Merkle.metadata_context() | nil
  defp merkle_for(:v1, _metadata), do: nil

  defp merkle_for(_kind, metadata) do
    case Torrent.Merkle.parse_metadata(metadata) do
      {:ok, context} ->
        context

      {:error, reason} ->
        raise ArgumentError, "invalid BitTorrent v2 merkle metadata: #{inspect(reason)}"
    end
  end

  @doc """
  Returns whether a torrent disables DHT peer discovery (BEP 27 de-facto `private` flag).
  """
  @spec private?(t() | map()) :: boolean()
  def private?(%__MODULE__{metadata: metadata}), do: private?(metadata)

  def private?(%{"info" => info}) when is_map(info), do: Magnet.private?(info)

  def private?(_), do: false

  # BEP 3: info_hash is SHA-1 of the raw bencoded `info` dict as it appears on
  # the wire. Re-encoding via Bento is unsafe — any non-canonical field ordering,
  # integer form, or byte difference produces the wrong hash and we silently
  # never find peers. Walk the outer dict, capture the slice for key "info".
  @spec slice_info_blob!(binary()) :: binary() | no_return()
  defp slice_info_blob!(<<"d", rest::binary>> = raw) do
    case find_info_slice(rest, raw) do
      {:ok, blob} -> blob
      :error -> raise ArgumentError, "torrent file missing info dictionary"
    end
  catch
    :invalid -> raise ArgumentError, "invalid bencoded torrent file"
  end

  defp slice_info_blob!(_),
    do: raise(ArgumentError, "torrent file is not a bencoded dictionary")

  defp find_info_slice(<<"e", _::binary>>, _raw), do: :error

  defp find_info_slice(bytes, raw) do
    {key, after_key} = bencode_string(bytes)
    value_start = byte_size(raw) - byte_size(after_key)
    {_value, after_value} = bencode_value(after_key)
    value_end = byte_size(raw) - byte_size(after_value)

    if key == "info" do
      {:ok, binary_part(raw, value_start, value_end - value_start)}
    else
      find_info_slice(after_value, raw)
    end
  end

  defp all_bytes_in_torrent(%{"info" => %{"length" => length}}), do: length

  defp all_bytes_in_torrent(%{"info" => %{"files" => list}}),
    do: Enum.reduce(list, 0, fn %{"length" => x}, acc -> x + acc end)

  # --- Minimal bencode scanner (byte-preserving) -----------------------------
  # Returns {parsed_value, rest_binary}. Throws :invalid on malformed input.

  defp bencode_value(<<"d", rest::binary>>), do: bencode_dict(rest, [])
  defp bencode_value(<<"l", rest::binary>>), do: bencode_list(rest, [])
  defp bencode_value(<<"i", rest::binary>>), do: bencode_int(rest, [])
  defp bencode_value(<<c, _::binary>> = str) when c in ?0..?9, do: bencode_string(str)
  defp bencode_value(_), do: throw(:invalid)

  defp bencode_int(<<"e", rest::binary>>, [_ | _] = acc),
    do: {acc |> Enum.reverse() |> IO.iodata_to_binary() |> String.to_integer(), rest}

  defp bencode_int(<<c, rest::binary>>, acc) when c in ?0..?9 or (acc == [] and c == ?-),
    do: bencode_int(rest, [c | acc])

  defp bencode_int(_, _), do: throw(:invalid)

  defp bencode_string(bytes), do: bencode_string_len(bytes, [])

  defp bencode_string_len(<<":", rest::binary>>, [_ | _] = acc) do
    len = acc |> Enum.reverse() |> IO.iodata_to_binary() |> String.to_integer()

    if len > byte_size(rest) do
      throw(:invalid)
    else
      {binary_part(rest, 0, len), binary_part(rest, len, byte_size(rest) - len)}
    end
  end

  defp bencode_string_len(<<c, rest::binary>>, acc) when c in ?0..?9,
    do: bencode_string_len(rest, [c | acc])

  defp bencode_string_len(_, _), do: throw(:invalid)

  defp bencode_list(<<"e", rest::binary>>, acc), do: {Enum.reverse(acc), rest}

  defp bencode_list(bytes, acc) do
    {value, rest} = bencode_value(bytes)
    bencode_list(rest, [value | acc])
  end

  defp bencode_dict(<<"e", rest::binary>>, acc), do: {Map.new(acc), rest}

  defp bencode_dict(bytes, acc) do
    {key, rest} = bencode_string(bytes)
    {value, rest} = bencode_value(rest)
    bencode_dict(rest, [{key, value} | acc])
  end
end
